#!/bin/bash

#
# This git hook is derrived from the github.com/soluble-ai/githooks
# repository and managed by the "soluble githook" command.
#
# Uncomment and/or modify the commands below.
#


# Check for hardcoded secrets in the source repository
#soluble secrets-scan

# Scan application dependencies for vulnerable packages/libraries
#soluble dep-scan trivy
#soluble dep-scan retirejs

# Scan (a built) container image
#soluble image-scan --image myimage:latest
