#!/bin/bash

#
# This git hook is derrived from the github.com/soluble-ai/githooks
# repository and managed by the "soluble githook" command.
#
# Uncomment and/or modify the commands below.
#


# Check for hardcoded secrets in the source repository
#soluble secrets-scan

# scan IaC content, automatically detecting IaC type
soluble auto-scan
# ...or uncomment below to run particular scanners
#soluble kubernetes-scan
#soluble terraform-scan
