name: Validate hooks
on:
  push:
    branches: [master]
  pull_request:

jobs:
  verify:
    timeout-minutes: 5
    name: Validate hooks
    runs-on: ubuntu-latest
    steps:
    - 
      name: Check out repo
      uses: actions/checkout@v2
    - 
      name: Generate hooks
      run: |
        make
    - 
      name: Ensure nil diff
      run: |
        git diff --quiet --exit-code ./app
        git diff --quiet --exit-code ./iac
